version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./app/data:/var/lib/postgresql/data
      - ./app/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./app/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db-net

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "8080:80"
#    depends_on:
#      - postgres
#    networks:
#      - db-net

  user-service:
    build:
      context: ./app/user_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${USER_SERVICE_INTERNAL_PORT}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_INTERNAL_PORT}"
    depends_on:
      - postgres
    networks:
      - db-net

  movie-service:
    build:
      context: app/movie_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${MOVIE_SERVICE_INTERNAL_PORT}
    ports:
      - "${MOVIE_SERVICE_PORT}:${MOVIE_SERVICE_INTERNAL_PORT}"
    depends_on:
      - postgres
    networks:
      - db-net
        
  recomendations-service:
    build:
      context: app/recomendations_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${RECOMENDATIONS_SERVICE_INTERNAL_PORT}
    ports:
      - "${RECOMENDATIONS_SERVICE_PORT}:${RECOMENDATIONS_SERVICE_INTERNAL_PORT}"
    depends_on:
      - postgres
    networks:
      - db-net


networks:
  db-net:
    driver: bridge