version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./app/data:/var/lib/postgresql/data
      - ./app/schema.sql:/schema.sql
      - ./app/seeds.sql:/seeds.sql
    ports:
      - "5432:5432"
    networks:
      - db-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - db-net

  user-service:
    image: user-service:local
    build:
      context: ./app/user_service
      dockerfile: Dockerfile
    ports:
      - "8082:80" 
    depends_on:
      - postgres
    networks:
      - db-net

networks:
  db-net:
    driver: bridge