version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./app/data:/var/lib/postgresql/data
      - ./app/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./app/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    ports:
      - "5432:5432"
    networks:
      - db-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - db-net

  user-service:
    build:
      context: ./app/user_service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - db-net

  movie-service:
    build:
      context: app/movie_service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - db-net

networks:
  db-net:
    driver: bridge